### ISSUE TITLE
MarioKart add-on for Blender

### ISSUE THREAD

**Issue by ghost** [leyyin/stk-blender#2]
Maybe, it could be usefull
* https://github.com/KillzXGaming/Mario-Kart-8-Blender-Path-XML-Exporter

P.S.: https://github.com/KillzXGaming/Mario-Kart-8-Blender-Path-XML-Exporter/issues/1

**Comment by auriamg** [comment]
Hmm no, it is not useful, we already have our own tools and the STK engine has nothing in common with the MK engine so there is no crossover possible.

Please, github tickets are for bug reports, this is not a bug report
